version: '3'

services:
  selenoid:
    image: selenoid/hub:latest
    volumes:
      - /usr/share/zoneinfo/Europe/Moscow:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./selenoid:/etc/selenoid
    environment:
      - DOCKER_API_VERSION=1.35
    command: ["-conf", "/etc/selenoid/browsers.json", '-container-network', 'crawler_default']
    expose:
      - 4444

  proxy:
    build:
      context: proxy
      dockerfile: Dockerfile
    restart: unless-stopped
    command: node server.js
    expose:
      - 5050
      - 8080
    volumes:
      - /usr/share/zoneinfo/Europe/Moscow:/etc/localtime:ro
      - ./var/log:/app/log

  flask:
    build:
      context: api
      dockerfile: Dockerfile
    restart: unless-stopped
    command: sh -c "uwsgi --ini=api/uwsgi.ini --strict --py-autoreload=1"
    volumes:
      - /usr/share/zoneinfo/Europe/Moscow:/etc/localtime:ro
      - ./api:/app/api
      - ./var:/app/var
    ports:
      - 3032:3032
