version: '3'

services:
  hub:
    image: selenium/hub:3.8.1
    environment:
      - GRID_TIMEOUT=45
      - GRID_MAX_SESSION=5
    expose:
      - 4444

  chrome:
    image: selenium/node-chrome:3.8.1
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=4
      - NODE_MAX_SESSION=4
    depends_on:
      - hub
    volumes:
      - /dev/shm:/dev/shm

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: flask
    environment:
      - FLASK_DEBUG=1
    command: sh -c "uwsgi --ini=uwsgi.ini --strict --py-autoreload=1"
    volumes:
      - .:/app
      - ./var:/app/var/

